### ISSUE TITLE
Update Play parsePlayURL script for RSI tv guide by channel

### ISSUE THREAD

**Issue by Loic-Dumas** [SRGSSR/playsrg-playfff#94]
### Issue type

**Feature request**

Handle https://www.rsi.ch/play/tv/guidatv-per-canale/* urls.

### Description of the problem

> The parsePlayUrl.js can't parse tv guide by channel urls.

Need to return a deeplink to access tvGuide.

**Comment by pyby** [comment]
We could add an optional query parameter with the `channelUrn` but it's an other story, as Android and iOS application to deal with as well.

Examples with the second channel:
- RSI: https://www.rsi.ch/play/tv/guidatv-per-canale/la-2/2024-05-06?channelUrn=urn%3Arsi%3Achannel%3Atv%3Ala2
- RTS: https://www.rts.ch/play/tv/programme-par-chaine/rts-2/2024-05-11?channelUrn=urn%3Arts%3Achannel%3Atv%3Ad7dfff28deee44e1d3c49a3d37d36d492b29671b
- SRF: https://www.srf.ch/play/tv/programm-nach-sender/srf-zwei/2024-05-11?channelUrn=urn%3Asrf%3Achannel%3Atv%3AE4D5AD08-C1E8-46A3-BB58-4875051D60D2
- RTR: https://www.rtr.ch/play/tv/tenor-program-tv/srf-zwei/2024-05-14?channelUrn=urn%3Asrf%3Achannel%3Atv%3AE4D5AD08-C1E8-46A3-BB58-4875051D60D2
